name: codecov
on: [push] 
    
env:
  
  hest:  foo
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Codecov
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@1fc7722ded4708880a5aea49f2bfafb9336f0c8d
        uses: codecov/codecov-action@v1.1.1
