name: Meson

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install clang-tidy ninja-build python3 gcovr lcov

    - name: Install mesons
      run: python3 -m pip install meson

    - name: Create Build Environment
      run: meson setup builddir -Db_coverage=true

    - name: Compile
      shell: bash
      working-directory: builddir
      run: ninja

    - name: Test
      working-directory: build
      shell: bash
      run: meson test

    - name: Coverage
      working-directory: build
      shell: bash
      run: ninja coverage-html
